// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tndgcypaguwxeizryfoj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRuZGdjeXBhZ3V3eGVpenJ5Zm9qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzNzYwMDMsImV4cCI6MjA2NTk1MjAwM30.bcaJXkjYtXJefotEf-k4hmdDa3IKGsdMFswHA8wzLHs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});